-- ============================================
-- ANALYTICS QUERIES
-- Advanced analysis
-- ============================================

-- 1. County farming percentages
SELECT COUNTY_NAME, TOTAL_HOUSEHOLDS, FARMING_HOUSEHOLDS,
       ROUND((FARMING_HOUSEHOLDS * 100.0 / TOTAL_HOUSEHOLDS), 2) AS FARMING_PERCENT
FROM COUNTIES
WHERE COUNTY_NAME != 'KENYA'
ORDER BY FARMING_HOUSEHOLDS DESC;

-- 2. Top crops by households
SELECT c.CROP_NAME, SUM(cas.HOUSEHOLDS_COUNT) AS TOTAL_HOUSEHOLDS
FROM CROPS c
JOIN COUNTY_AGRIC_STATS cas ON c.CROP_ID = cas.CROP_ID
WHERE cas.CROP_ID IS NOT NULL
GROUP BY c.CROP_NAME
ORDER BY TOTAL_HOUSEHOLDS DESC;

-- 3. Livestock distribution
SELECT lt.ANIMAL_NAME, SUM(cas.HOUSEHOLDS_COUNT) AS TOTAL_HOUSEHOLDS
FROM LIVESTOCK_TYPES lt
JOIN COUNTY_AGRIC_STATS cas ON lt.LIVESTOCK_ID = cas.LIVESTOCK_ID
WHERE cas.LIVESTOCK_ID IS NOT NULL
GROUP BY lt.ANIMAL_NAME
ORDER BY TOTAL_HOUSEHOLDS DESC;

-- 4. Farming activities analysis
SELECT fa.ACTIVITY_NAME, SUM(cas.HOUSEHOLDS_COUNT) AS TOTAL_HOUSEHOLDS
FROM FARMING_ACTIVITIES fa
JOIN COUNTY_AGRIC_STATS cas ON fa.ACTIVITY_ID = cas.ACTIVITY_ID
WHERE cas.ACTIVITY_ID IS NOT NULL
GROUP BY fa.ACTIVITY_NAME
ORDER BY TOTAL_HOUSEHOLDS DESC;

-- 5. County comparison
SELECT COUNTY_NAME, FARMING_HOUSEHOLDS,
       RANK() OVER (ORDER BY FARMING_HOUSEHOLDS DESC) AS RANK_POSITION
FROM COUNTIES
WHERE COUNTY_NAME != 'KENYA';

-- 6. Crop vs Livestock comparison
SELECT 
    'CROP' AS TYPE,
    COUNT(DISTINCT cas.CROP_ID) AS ITEM_COUNT,
    SUM(cas.HOUSEHOLDS_COUNT) AS TOTAL_HOUSEHOLDS
FROM COUNTY_AGRIC_STATS cas
WHERE cas.CROP_ID IS NOT NULL
UNION ALL
SELECT 
    'LIVESTOCK',
    COUNT(DISTINCT cas.LIVESTOCK_ID),
    SUM(cas.HOUSEHOLDS_COUNT)
FROM COUNTY_AGRIC_STATS cas
WHERE cas.LIVESTOCK_ID IS NOT NULL;