-- ============================================
-- AUDIT QUERIES
-- Monitoring queries
-- ============================================

-- 1. Audit summary
SELECT OPERATION_STATUS, COUNT(*) AS COUNT
FROM AGRIC_SURVEY_AUDIT
GROUP BY OPERATION_STATUS;

-- 2. User activity
SELECT USERNAME, USER_TYPE, COUNT(*) AS OPERATION_COUNT
FROM AGRIC_SURVEY_AUDIT
GROUP BY USERNAME, USER_TYPE
ORDER BY OPERATION_COUNT DESC;

-- 3. Table operations
SELECT TABLE_NAME, DML_OPERATION, COUNT(*) AS COUNT
FROM AGRIC_SURVEY_AUDIT
GROUP BY TABLE_NAME, DML_OPERATION
ORDER BY TABLE_NAME, DML_OPERATION;

-- 4. Denied operations
SELECT USERNAME, TABLE_NAME, DML_OPERATION, DENIAL_REASON
FROM AGRIC_SURVEY_AUDIT
WHERE OPERATION_STATUS = 'DENIED';

-- 5. Successful operations
SELECT USER_TYPE, TABLE_NAME, DML_OPERATION, COUNT(*) AS COUNT
FROM AGRIC_SURVEY_AUDIT
WHERE OPERATION_STATUS = 'ALLOWED'
GROUP BY USER_TYPE, TABLE_NAME, DML_OPERATION
ORDER BY COUNT DESC;

-- 6. Survey period compliance
SELECT IS_WITHIN_PERIOD, OPERATION_STATUS, COUNT(*) AS COUNT
FROM AGRIC_SURVEY_AUDIT
GROUP BY IS_WITHIN_PERIOD, OPERATION_STATUS;

-- 7. Recent audit activity
SELECT USERNAME, TABLE_NAME, DML_OPERATION, OPERATION_STATUS, AUDIT_TIMESTAMP
FROM AGRIC_SURVEY_AUDIT
ORDER BY AUDIT_TIMESTAMP DESC;