-- ============================================
-- DATA RETRIEVAL QUERIES
-- Basic SELECT queries
-- ============================================

-- 1. Get county data
SELECT COUNTY_ID, COUNTY_NAME, TOTAL_HOUSEHOLDS, FARMING_HOUSEHOLDS
FROM COUNTIES 
WHERE ROWNUM <= 10;

-- 2. Get crop types
SELECT CROP_ID, CROP_NAME, CATEGORY
FROM CROPS
ORDER BY CATEGORY;

-- 3. Get livestock types
SELECT LIVESTOCK_ID, ANIMAL_NAME, CATEGORY
FROM LIVESTOCK_TYPES
ORDER BY CATEGORY;

-- 4. Get farming activities
SELECT ACTIVITY_ID, ACTIVITY_NAME, DESCRIPTION
FROM FARMING_ACTIVITIES;

-- 5. Get agricultural statistics
SELECT cas.STAT_ID, c.COUNTY_NAME, 
       COALESCE(cr.CROP_NAME, lt.ANIMAL_NAME, fa.ACTIVITY_NAME) AS ITEM,
       cas.HOUSEHOLDS_COUNT
FROM COUNTY_AGRIC_STATS cas
JOIN COUNTIES c ON cas.COUNTY_ID = c.COUNTY_ID
LEFT JOIN CROPS cr ON cas.CROP_ID = cr.CROP_ID
LEFT JOIN LIVESTOCK_TYPES lt ON cas.LIVESTOCK_ID = lt.LIVESTOCK_ID
LEFT JOIN FARMING_ACTIVITIES fa ON cas.ACTIVITY_ID = fa.ACTIVITY_ID
WHERE ROWNUM <= 15;

-- 6. Get survey periods
SELECT PERIOD_ID, SURVEY_NAME, START_DATE, END_DATE, STATUS
FROM SURVEY_COLLECTION_PERIODS;

-- 7. Get system users
SELECT USER_ID, USERNAME, USER_TYPE, FULL_NAME
FROM SYSTEM_USERS;

-- 8. Get audit log
SELECT AUDIT_ID, USERNAME, TABLE_NAME, DML_OPERATION, OPERATION_STATUS
FROM AGRIC_SURVEY_AUDIT
WHERE ROWNUM <= 10;